# Change these first
owner: h476982844
repo: upptime # The name of this repository

sites:
  - name: 极彩 multicolor
    url: https://multicolor.club
  - name: 夕月幻想俱乐部
    url: https://moon-rise.cn
  - name: 失落的安提基特拉 
    url: https://antikythera.moon-rise.cn/api/healthz

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: upptime.moon-rise.tech
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: UppTime
  introTitle: "八意豆子的服务又挂了"
  introMessage: "让我我们狠狠笑话他"
  navbar:
    - title: Status
      href: /

workflowSchedule:
  uptime: "*/30 * * * *"
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
